server:
  port: 8080

spring:
  application:
    name: TanishqCare
  datasource:
    url: jdbc:h2:tcp://localhost/./esha;IFEXISTS=TRUE
    platform: h2
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true